pub enum AfricaRegion {
    Algeria,
    Angola,
    Benin,
    Botswana,
    BurkinaFaso,
    Burundi,
    Cameroon,
    CanaryIslands,
    CapeVerde,
    CentralAfricanRepublic,
    Chad,
    Comores,
    CongoBrazzaville,
    CongoDemocraticRepublic,
    Djibouti,
    Egypt,
    EquatorialGuinea,
    Eritrea,
    Ethiopia,
    Gabon,
    Ghana,
    GuineaBissau,
    Guinea,
    IvoryCoast,
    Kenya,
    Lesotho,
    Liberia,
    Libya,
    Madagascar,
    Malawi,
    Mali,
    Mauritania,
    Mauritius,
    Morocco,
    Mozambique,
    Namibia,
    Niger,
    Nigeria,
    Rwanda,
    SaintHelenaAscensionAndTristanDaCunha,
    SaoTomeAndPrincipe,
    SenegalAndGambia,
    Seychelles,
    SierraLeone,
    Somalia,
    SouthAfricaAndLesotho,
    SouthAfrica,
    SouthSudan,
    Sudan,
    Swaziland,
    Tanzania,
    Togo,
    Tunisia,
    Uganda,
    Zambia,
    Zimbabwe,
}

impl AfricaRegion {
    pub fn path(&self) -> &'static str {
        match self {
            Self::Algeria => "africa/algeria",
            Self::Angola => "africa/angola",
            Self::Benin => "africa/benin",
            Self::Botswana => "africa/botswana",
            Self::BurkinaFaso => "africa/burkina-faso",
            Self::Burundi => "africa/burundi",
            Self::Cameroon => "africa/cameroon",
            Self::CanaryIslands => "africa/canary-islands",
            Self::CapeVerde => "africa/cape-verde",
            Self::CentralAfricanRepublic => "africa/central-african-republic",
            Self::Chad => "africa/chad",
            Self::Comores => "africa/comores",
            Self::CongoBrazzaville => "africa/congo-brazzaville",
            Self::CongoDemocraticRepublic => "africa/congo-democratic-republic",
            Self::Djibouti => "africa/djibouti",
            Self::Egypt => "africa/egypt",
            Self::EquatorialGuinea => "africa/equatorial-guinea",
            Self::Eritrea => "africa/eritrea",
            Self::Ethiopia => "africa/ethiopia",
            Self::Gabon => "africa/gabon",
            Self::Ghana => "africa/ghana",
            Self::GuineaBissau => "africa/guinea-bissau",
            Self::Guinea => "africa/guinea",
            Self::IvoryCoast => "africa/ivory-coast",
            Self::Kenya => "africa/kenya",
            Self::Lesotho => "africa/lesotho",
            Self::Liberia => "africa/liberia",
            Self::Libya => "africa/libya",
            Self::Madagascar => "africa/madagascar",
            Self::Malawi => "africa/malawi",
            Self::Mali => "africa/mali",
            Self::Mauritania => "africa/mauritania",
            Self::Mauritius => "africa/mauritius",
            Self::Morocco => "africa/morocco",
            Self::Mozambique => "africa/mozambique",
            Self::Namibia => "africa/namibia",
            Self::Niger => "africa/niger",
            Self::Nigeria => "africa/nigeria",
            Self::Rwanda => "africa/rwanda",
            Self::SaintHelenaAscensionAndTristanDaCunha => {
                "africa/saint-helena-ascension-and-tristan-da-cunha"
            }
            Self::SaoTomeAndPrincipe => "africa/sao-tome-and-principe",
            Self::SenegalAndGambia => "africa/senegal-and-gambia",
            Self::Seychelles => "africa/seychelles",
            Self::SierraLeone => "africa/sierra-leone",
            Self::Somalia => "africa/somalia",
            Self::SouthAfricaAndLesotho => "africa/south-africa-and-lesotho",
            Self::SouthAfrica => "africa/south-africa",
            Self::SouthSudan => "africa/south-sudan",
            Self::Sudan => "africa/sudan",
            Self::Swaziland => "africa/swaziland",
            Self::Tanzania => "africa/tanzania",
            Self::Togo => "africa/togo",
            Self::Tunisia => "africa/tunisia",
            Self::Uganda => "africa/uganda",
            Self::Zambia => "africa/zambia",
            Self::Zimbabwe => "africa/zimbabwe",
        }
    }
}
