pub enum AsiaRegion {
    Afghanistan,
    Armenia,
    Azerbaijan,
    Bangladesh,
    Bhutan,
    Cambodia,
    China,
    EastTimor,
    GccStates,
    India,
    Indonesia,
    Iran,
    Iraq,
    IsraelAndPalestine,
    Japan,
    Jordan,
    Kazakhstan,
    Kyrgyzstan,
    Laos,
    Lebanon,
    MalaysiaSingaporeBrunei,
    Maldives,
    Mongolia,
    Myanmar,
    Nepal,
    NorthKorea,
    Pakistan,
    Philippines,
    SouthKorea,
    SriLanka,
    Syria,
    Taiwan,
    Tajikistan,
    Thailand,
    Turkmenistan,
    Uzbekistan,
    Vietnam,
    Yemen,
}

impl AsiaRegion {
    pub fn path(&self) -> &'static str {
        match self {
            Self::Afghanistan => "asia/afghanistan",
            Self::Armenia => "asia/armenia",
            Self::Azerbaijan => "asia/azerbaijan",
            Self::Bangladesh => "asia/bangladesh",
            Self::Bhutan => "asia/bhutan",
            Self::Cambodia => "asia/cambodia",
            Self::China => "asia/china",
            Self::EastTimor => "asia/east-timor",
            Self::GccStates => "asia/gcc-states",
            Self::India => "asia/india",
            Self::Indonesia => "asia/indonesia",
            Self::Iran => "asia/iran",
            Self::Iraq => "asia/iraq",
            Self::IsraelAndPalestine => "asia/israel-and-palestine",
            Self::Japan => "asia/japan",
            Self::Jordan => "asia/jordan",
            Self::Kazakhstan => "asia/kazakhstan",
            Self::Kyrgyzstan => "asia/kyrgyzstan",
            Self::Laos => "asia/laos",
            Self::Lebanon => "asia/lebanon",
            Self::MalaysiaSingaporeBrunei => "asia/malaysia-singapore-brunei",
            Self::Maldives => "asia/maldives",
            Self::Mongolia => "asia/mongolia",
            Self::Myanmar => "asia/myanmar",
            Self::Nepal => "asia/nepal",
            Self::NorthKorea => "asia/north-korea",
            Self::Pakistan => "asia/pakistan",
            Self::Philippines => "asia/philippines",
            Self::SouthKorea => "asia/south-korea",
            Self::SriLanka => "asia/sri-lanka",
            Self::Syria => "asia/syria",
            Self::Taiwan => "asia/taiwan",
            Self::Tajikistan => "asia/tajikistan",
            Self::Thailand => "asia/thailand",
            Self::Turkmenistan => "asia/turkmenistan",
            Self::Uzbekistan => "asia/uzbekistan",
            Self::Vietnam => "asia/vietnam",
            Self::Yemen => "asia/yemen",
        }
    }
}
