pub enum EuropeRegion {
    Albania,
    Alps,
    Andorra,
    Austria,
    Azores,
    Belarus,
    Belgium,
    BosniaHerzegovina,
    BritainAndIreland,
    Bulgaria,
    Croatia,
    Cyprus,
    CzechRepublic,
    Dach,
    Denmark,
    Estonia,
    FaroeIslands,
    Finland,
    France,
    Georgia,
    Germany,
    Greece,
    GuernseyJersey,
    Hungary,
    Iceland,
    IrelandAndNorthernIreland,
    IsleOfMan,
    Italy,
    Kosovo,
    Latvia,
    Liechtenstein,
    Lithuania,
    Luxembourg,
    Macedonia,
    Malta,
    Moldova,
    Monaco,
    Montenegro,
    Netherlands,
    Norway,
    Poland,
    Portugal,
    Romania,
    Serbia,
    Slovakia,
    Slovenia,
    Spain,
    Sweden,
    Switzerland,
    Turkey,
    Ukraine,
    UnitedKingdom,
}

impl EuropeRegion {
    pub fn path(&self) -> &'static str {
        match self {
            Self::Albania => "europe/albania",
            Self::Alps => "europe/alps",
            Self::Andorra => "europe/andorra",
            Self::Austria => "europe/austria",
            Self::Azores => "europe/azores",
            Self::Belarus => "europe/belarus",
            Self::Belgium => "europe/belgium",
            Self::BosniaHerzegovina => "europe/bosnia-herzegovina",
            Self::BritainAndIreland => "europe/britain-and-ireland",
            Self::Bulgaria => "europe/bulgaria",
            Self::Croatia => "europe/croatia",
            Self::Cyprus => "europe/cyprus",
            Self::CzechRepublic => "europe/czech-republic",
            Self::Dach => "europe/dach",
            Self::Denmark => "europe/denmark",
            Self::Estonia => "europe/estonia",
            Self::FaroeIslands => "europe/faroe-islands",
            Self::Finland => "europe/finland",
            Self::France => "europe/france",
            Self::Georgia => "europe/georgia",
            Self::Germany => "europe/germany",
            Self::Greece => "europe/greece",
            Self::GuernseyJersey => "europe/guernsey-jersey",
            Self::Hungary => "europe/hungary",
            Self::Iceland => "europe/iceland",
            Self::IrelandAndNorthernIreland => {
                "europe/ireland-and-northern-ireland"
            }
            Self::IsleOfMan => "europe/isle-of-man",
            Self::Italy => "europe/italy",
            Self::Kosovo => "europe/kosovo",
            Self::Latvia => "europe/latvia",
            Self::Liechtenstein => "europe/liechtenstein",
            Self::Lithuania => "europe/lithuania",
            Self::Luxembourg => "europe/luxembourg",
            Self::Macedonia => "europe/macedonia",
            Self::Malta => "europe/malta",
            Self::Moldova => "europe/moldova",
            Self::Monaco => "europe/monaco",
            Self::Montenegro => "europe/montenegro",
            Self::Netherlands => "europe/netherlands",
            Self::Norway => "europe/norway",
            Self::Poland => "europe/poland",
            Self::Portugal => "europe/portugal",
            Self::Romania => "europe/romania",
            Self::Serbia => "europe/serbia",
            Self::Slovakia => "europe/slovakia",
            Self::Slovenia => "europe/slovenia",
            Self::Spain => "europe/spain",
            Self::Sweden => "europe/sweden",
            Self::Switzerland => "europe/switzerland",
            Self::Turkey => "europe/turkey",
            Self::Ukraine => "europe/ukraine",
            Self::UnitedKingdom => "europe/united-kingdom",
        }
    }
}
